server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.136.204.127:1111/java3auth
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}